name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Test application
      run: |
        python -c "
        from calculadora import calcular_tmb_homem, calcular_tmb_mulher
        print('Testando TMB para homem:', calcular_tmb_homem(70, 175, 30))
        print('Testando TMB para mulher:', calcular_tmb_mulher(60, 165, 25))
        print('Teste concluído com sucesso!')
        "
