name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  # Job de CI (Continuous Integration)
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run unit tests
      run: |
        python -m unittest calculadora.py

    - name: Notificar Discord - Testes
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "🧪 Testes Executados - ${{ job.status }}"
        description: |
          Repositório: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Executado por: ${{ github.actor }}
        color: ${{ job.status == 'success' && '00ff00' || 'ff0000' }}

  # Job de CD (Continuous Deployment)
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Test application functionality
      run: |
        python -c "
        from calculadora import calcular_tmb_homem, calcular_tmb_mulher
        print('Testando TMB para homem (70kg, 175cm, 30 anos):', calcular_tmb_homem(70, 175, 30))
        print('Testando TMB para mulher (60kg, 165cm, 25 anos):', calcular_tmb_mulher(60, 165, 25))
        print('Teste de implantação concluído com sucesso!')
        "
        
    - name: Simulate deployment
      run: |
        echo "Simulando processo de deployment..."
        echo "✅ Aplicação pronta para produção!"

    - name: Notificar Discord - Deploy
      uses: sarisia/actions-status-discord@v1
      if: success()
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "🚀 Deploy Realizado com Sucesso!"
        description: |
          Repositório: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
        color: "00ff00"
