name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  # Job de CI (Continuous Integration)
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run unit tests
      run: |
        python -m unittest calculadora.py

    - name: Notificar Discord - Testes
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const webhookURL = process.env.DISCORD_WEBHOOK_URL;
          if (!webhookURL) {
            console.log('Discord webhook not configured');
            return;
          }
          
          const status = '${{ job.status }}';
          const emoji = status === 'success' ? '✅' : '❌';
          
          const payload = {
            content: `${emoji} **Testes ${{ job.status }}**\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}`
          };
          
          await fetch(webhookURL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });

  # Job de CD (Continuous Deployment)
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Test application functionality
      run: |
        python -c "
        from calculadora import calcular_tmb_homem, calcular_tmb_mulher
        print('Testando TMB para homem (70kg, 175cm, 30 anos):', calcular_tmb_homem(70, 175, 30))
        print('Testando TMB para mulher (60kg, 165cm, 25 anos):', calcular_tmb_mulher(60, 165, 25))
        print('Teste de implantação concluído com sucesso!')
        "
        
    - name: Simulate deployment
      run: |
        echo "Simulando processo de deployment..."
        echo "✅ Aplicação pronta para produção!"

    - name: Notificar Discord - Deploy
      if: success()
      uses: actions/github-script@v6
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        script: |
          const webhookURL = process.env.DISCORD_WEBHOOK_URL;
          if (!webhookURL) {
            console.log('Discord webhook not configured');
            return;
          }
          
          const payload = {
            content: "🚀 **Deploy Realizado com Sucesso!**\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}"
          };
          
          await fetch(webhookURL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });
